[local]
localhost

[mongodb]
mongodb.devopswithrani.online 

[redis]
redis.devopswithrani.online 

[mysql]
mysql.devopswithrani.online 

[rabbitmq]
rabbitmq.devopswithrani.online 

[catalogue]
catalogue.devopswithrani.online 

[user]
user.devopswithrani.online 

[cart]
cart.devopswithrani.online 

[shipping]
shipping.devopswithrani.online 

[payment]
payment.devopswithrani.online 

[frontend]
frontend.devopswithrani.online 