ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb.devopswithrani.online
REDIS_HOST: redis.devopswithrani.online
MYSQL_HOST: mysql.devopswithrani.online
RABBITMQ_HOST: rabbitmq.devopswithrani.online
CATALOGUE_HOST: catalogue.devopswithrani.online
USER_HOST: user.devopswithrani.online
CART_HOST: cart.devopswithrani.online 
SHIPPING_HOST: shipping.devopswithrani.online 
PAYMENT_HOST: payment.devopswithrani.online 